### ISSUE TITLE
Support AudioBufferSourceNode.start() offset and duration params

### ISSUE THREAD

**Issue by ferjm** [servo/media#149]
https://webaudio.github.io/web-audio-api/#dom-audiobuffersourcenode-start

**Comment by Manishearth** [comment]
The duration parameter is tricky because it's handled in the AudioBuffer's time domain (taking into account playbackRate and the fact that the buffer may have a different sample rate)

We should probably implement playbackRate, loop, and duration/offset together 

https://webaudio.github.io/web-audio-api/#playback-AudioBufferSourceNode

I started working on this in [this branch](https://github.com/servo/servo/compare/master...Manishearth:absn-start?expand=1) but I'd rather continue poking at other failures for now, so feel free to take over from there!

**Comment by Manishearth** [comment]
Note that this requires resampling which can be tricky. For now we can "resample" taking averages or just rounding, and later try to fix it. The actual resampling code can be complex.

**Comment by ferjm** [comment]
Tracked in https://github.com/servo/servo/issues/22363
