### ISSUE TITLE
Race condition in GStreamer decoder

### ISSUE THREAD

**Issue by Manishearth** [servo/media#151]
The audio_decoder example occasionally panics on [this assertion](https://github.com/servo/media/blob/master/audio/src/buffer_source_node.rs#L201). This happens a lot on CI (which has "1.5 threads" IIRC) but less so locally.

I investigated it a bit (it's pretty easy to reproduce under rr's chaos mode, `rr record -h target/debug/audio_decoder`).

The problem is that gstreamer decodes things on multiple threads (per-channel as far as I can tell), which both call [`new_sample()`](https://github.com/servo/media/blob/b274b9636d4f90e44835735279674c1279e75592/backends/gstreamer/src/audio_decoder.rs#L176). When it reaches the end, [`eos()`](https://github.com/servo/media/blob/b274b9636d4f90e44835735279674c1279e75592/backends/gstreamer/src/audio_decoder.rs#L233) gets called. However, the `new_sample()` from the other thread may not have run yet -- `eos()` isn't guaranteed to run _after_ all of the `new_sample()` calls finish.

One possible fix is to have a second RWlock -- always read-acquired by `new_sample()`. `eos()` write-acquires it and first drains `appsink.pull_sample()` into the buffers before sending the actual EOS signal. This is kinda ugly, I'm hoping there's a way we can ensure eos gets called after everything else, or have a way to wait in eos for everything to finish.

cc @ferjm @sdroege

**Comment by sdroege** [comment]
By using `deinterleave` and `queue`s after it, each of the following `appsink` will get its data from a different thread. That's correct.

The problem here is (if I understand your callbacks correctly) that, while each `appsink` will always have both callbacks called from the same thread (there won't be an `eos` for the same `appsink` during `new-sample`, it will only be triggered *after* the last `new-sample` callback has returned from the very same thread), you have multiple `appsink`. You need to wait for the `eos` callback of *all* of them before considering things to be finished, e.g. by using a simple counter.

I don't know how your exact pipeline looks like, but if the `appsink`s are the only sinks in this pipeline (or you want to wait for all sinks to finish) you could also leave the counting to GStreamer and make use of the `Eos` message from the bus (that message will only appear once *every* sink has received their `Eos` event, the event that triggers the `eos` callback on `appsink). You could wait for it in the sync handler you already have in this code and trigger "global" end-of-stream from there instead of directly from the `appsink`s.
